version: rv00
type: AutotaggingRunner
optimizer:
  type: Adam
  params:
    learning_rate: 1e-5
    scale_factor: 5
scheduler:
  type: ExponentialLR
  params:
    gamma: 0.95
trainer:
  type: Trainer
  params:
    max_epochs: 100
    gpus: 1
    distributed_backend: dp # train.py: ddp, evaluate.py: dp
    benchmark: False
    deterministic: True